// ABOUTME: Curated city lists for the travel checklist feature.
// ABOUTME: Contains Top 50 Largest Cities (UN) and UNESCO World Heritage Cities.

export const CITY_LISTS = {
  'top50': {
    name: "World's 50 Largest Cities",
    source: 'UN World Urbanization Prospects 2025 via Worldometers',
    cities: [
      {name: 'Jakarta', country: 'Indonesia'},
      {name: 'Dhaka', country: 'Bangladesh'},
      {name: 'Tokyo', country: 'Japan'},
      {name: 'New Delhi', country: 'India'},
      {name: 'Shanghai', country: 'China'},
      {name: 'Guangzhou', country: 'China'},
      {name: 'Cairo', country: 'Egypt'},
      {name: 'Manila', country: 'Philippines'},
      {name: 'Kolkata', country: 'India'},
      {name: 'Seoul', country: 'South Korea'},
      {name: 'Karachi', country: 'Pakistan'},
      {name: 'Mumbai', country: 'India'},
      {name: 'São Paulo', country: 'Brazil'},
      {name: 'Bangkok', country: 'Thailand'},
      {name: 'Mexico City', country: 'Mexico'},
      {name: 'Beijing', country: 'China'},
      {name: 'Lahore', country: 'Pakistan'},
      {name: 'Istanbul', country: 'Turkey'},
      {name: 'Moscow', country: 'Russia'},
      {name: 'Ho Chi Minh City', country: 'Vietnam'},
      {name: 'Buenos Aires', country: 'Argentina'},
      {name: 'New York City', country: 'United States of America'},
      {name: 'Shenzhen', country: 'China'},
      {name: 'Bengaluru', country: 'India'},
      {name: 'Osaka', country: 'Japan'},
      {name: 'Lagos', country: 'Nigeria'},
      {name: 'Los Angeles', country: 'United States of America'},
      {name: 'Luanda', country: 'Angola'},
      {name: 'Chennai', country: 'India'},
      {name: 'Kinshasa', country: 'Dem. Rep. Congo'},
      {name: 'Bogotá', country: 'Colombia'},
      {name: 'Lima', country: 'Peru'},
      {name: 'London', country: 'United Kingdom'},
      {name: 'Patna', country: 'India'},
      {name: 'Rio de Janeiro', country: 'Brazil'},
      {name: 'Paris', country: 'France'},
      {name: 'Hyderabad', country: 'India'},
      {name: 'Tehran', country: 'Iran'},
      {name: 'Taipei', country: 'Taiwan'},
      {name: 'Bandung', country: 'Indonesia'},
      {name: 'Kuala Lumpur', country: 'Malaysia'},
      {name: 'Dar es Salaam', country: 'Tanzania'},
      {name: 'Suzhou', country: 'China'},
      {name: 'Ahmedabad', country: 'India'},
      {name: 'Hangzhou', country: 'China'},
      {name: 'Wuhan', country: 'China'},
      {name: 'Tianjin', country: 'China'},
      {name: 'Alexandria', country: 'Egypt'},
      {name: 'Nagoya', country: 'Japan'},
      {name: 'Johannesburg', country: 'South Africa'},
    ],
  },

  'unesco': {
    name: 'UNESCO World Heritage Cities',
    source: 'UNESCO World Heritage Centre — Historic City Centres',
    cities: [
      {name: 'Quito', country: 'Ecuador', year: 1978},
      {name: 'Kraków', country: 'Poland', year: 1978},
      {name: 'Antigua Guatemala', country: 'Guatemala', year: 1979},
      {name: 'Split', country: 'Croatia', year: 1979},
      {name: 'Dubrovnik', country: 'Croatia', year: 1979},
      {name: 'Damascus', country: 'Syria', year: 1979},
      {name: 'Cairo', country: 'Egypt', year: 1979},
      {name: 'Tunis', country: 'Tunisia', year: 1979},
      {name: 'Kotor', country: 'Montenegro', year: 1979},
      {name: 'Ohrid', country: 'North Macedonia', year: 1979},
      {name: 'Rome', country: 'Italy', year: 1980},
      {name: 'Ouro Preto', country: 'Brazil', year: 1980},
      {name: 'Warsaw', country: 'Poland', year: 1980},
      {name: 'Valletta', country: 'Malta', year: 1980},
      {name: 'Bosra', country: 'Syria', year: 1980},
      {name: 'Fez', country: 'Morocco', year: 1981},
      {name: 'Jerusalem', country: 'Israel', year: 1981},
      {name: 'Olinda', country: 'Brazil', year: 1982},
      {name: 'Havana', country: 'Cuba', year: 1982},
      {name: 'Shibam', country: 'Yemen', year: 1982},
      {name: 'Berne', country: 'Switzerland', year: 1983},
      {name: 'Nessebar', country: 'Bulgaria', year: 1983},
      {name: 'Cuzco', country: 'Peru', year: 1983},
      {name: 'Córdoba', country: 'Spain', year: 1984},
      {name: 'Cartagena', country: 'Colombia', year: 1984},
      {name: 'Istanbul', country: 'Turkey', year: 1985},
      {name: 'Salvador de Bahia', country: 'Brazil', year: 1985},
      {name: 'Quebec City', country: 'Canada', year: 1985},
      {name: 'Marrakesh', country: 'Morocco', year: 1985},
      {name: 'Segovia', country: 'Spain', year: 1985},
      {name: 'Santiago de Compostela', country: 'Spain', year: 1985},
      {name: 'Ávila', country: 'Spain', year: 1985},
      {name: 'Aleppo', country: 'Syria', year: 1986},
      {name: 'Évora', country: 'Portugal', year: 1986},
      {name: 'Toledo', country: 'Spain', year: 1986},
      {name: 'Cáceres', country: 'Spain', year: 1986},
      {name: 'Sana\'a', country: 'Yemen', year: 1986},
      {name: 'Lübeck', country: 'Germany', year: 1987},
      {name: 'Mexico City', country: 'Mexico', year: 1987},
      {name: 'Oaxaca', country: 'Mexico', year: 1987},
      {name: 'Puebla', country: 'Mexico', year: 1987},
      {name: 'Venice', country: 'Italy', year: 1987},
      {name: 'Potosí', country: 'Bolivia', year: 1987},
      {name: 'Lima', country: 'Peru', year: 1988},
      {name: 'Guanajuato', country: 'Mexico', year: 1988},
      {name: 'Sousse', country: 'Tunisia', year: 1988},
      {name: 'Salamanca', country: 'Spain', year: 1988},
      {name: 'Djenné', country: 'Mali', year: 1988},
      {name: 'Strasbourg', country: 'France', year: 1988},
      {name: 'Kairouan', country: 'Tunisia', year: 1988},
      {name: 'Rhodes', country: 'Greece', year: 1988},
      {name: 'Santo Domingo', country: 'Dominican Republic', year: 1990},
      {name: 'Saint Petersburg', country: 'Russia', year: 1990},
      {name: 'San Gimignano', country: 'Italy', year: 1990},
      {name: 'Morelia', country: 'Mexico', year: 1991},
      {name: 'Sucre', country: 'Bolivia', year: 1991},
      {name: 'Rauma', country: 'Finland', year: 1991},
      {name: 'Ayutthaya', country: 'Thailand', year: 1991},
      {name: 'Sukhothai', country: 'Thailand', year: 1991},
      {name: 'Český Krumlov', country: 'Czechia', year: 1992},
      {name: 'Prague', country: 'Czechia', year: 1992},
      {name: 'Telč', country: 'Czechia', year: 1992},
      {name: 'Goslar', country: 'Germany', year: 1992},
      {name: 'Algiers', country: 'Algeria', year: 1992},
      {name: 'Bukhara', country: 'Uzbekistan', year: 1993},
      {name: 'Zacatecas', country: 'Mexico', year: 1993},
      {name: 'Banská Štiavnica', country: 'Slovakia', year: 1993},
      {name: 'Bamberg', country: 'Germany', year: 1993},
      {name: 'Zabid', country: 'Yemen', year: 1993},
      {name: 'Vilnius', country: 'Lithuania', year: 1994},
      {name: 'Safranbolu', country: 'Turkey', year: 1994},
      {name: 'Luxembourg City', country: 'Luxembourg', year: 1994},
      {name: 'Quedlinburg', country: 'Germany', year: 1994},
      {name: 'Avignon', country: 'France', year: 1995},
      {name: 'Naples', country: 'Italy', year: 1995},
      {name: 'Siena', country: 'Italy', year: 1995},
      {name: 'Colonia del Sacramento', country: 'Uruguay', year: 1995},
      {name: 'Kutná Hora', country: 'Czechia', year: 1995},
      {name: 'Visby', country: 'Sweden', year: 1995},
      {name: 'Luang Prabang', country: 'Laos', year: 1995},
      {name: 'Lunenburg', country: 'Canada', year: 1995},
      {name: 'Edinburgh', country: 'United Kingdom', year: 1995},
      {name: 'Mompox', country: 'Colombia', year: 1995},
      {name: 'Porto', country: 'Portugal', year: 1996},
      {name: 'Pienza', country: 'Italy', year: 1996},
      {name: 'Salzburg', country: 'Austria', year: 1996},
      {name: 'Meknes', country: 'Morocco', year: 1996},
      {name: 'Querétaro', country: 'Mexico', year: 1996},
      {name: 'Cuenca', country: 'Spain', year: 1996},
      {name: 'Poreč', country: 'Croatia', year: 1997},
      {name: 'Tallinn', country: 'Estonia', year: 1997},
      {name: 'Riga', country: 'Latvia', year: 1997},
      {name: 'São Luís', country: 'Brazil', year: 1997},
      {name: 'Trogir', country: 'Croatia', year: 1997},
      {name: 'Carcassonne', country: 'France', year: 1997},
      {name: 'Lijiang', country: 'China', year: 1997},
      {name: 'Ping Yao', country: 'China', year: 1997},
      {name: 'Tétouan', country: 'Morocco', year: 1997},
      {name: 'Willemstad', country: 'Netherlands', year: 1997},
      {name: 'Tlacotalpan', country: 'Mexico', year: 1998},
      {name: 'Urbino', country: 'Italy', year: 1998},
      {name: 'Lviv', country: 'Ukraine', year: 1998},
      {name: 'Alcalá de Henares', country: 'Spain', year: 1998},
      {name: 'Lyon', country: 'France', year: 1998},
      {name: 'Cuenca', country: 'Ecuador', year: 1999},
      {name: 'Graz', country: 'Austria', year: 1999},
      {name: 'Sighișoara', country: 'Romania', year: 1999},
      {name: 'Diamantina', country: 'Brazil', year: 1999},
      {name: 'Vigan', country: 'Philippines', year: 1999},
      {name: 'Campeche', country: 'Mexico', year: 1999},
      {name: 'Hoi An', country: 'Vietnam', year: 1999},
      {name: 'Bruges', country: 'Belgium', year: 2000},
      {name: 'Shakhrisabz', country: 'Uzbekistan', year: 2000},
      {name: 'Arequipa', country: 'Peru', year: 2000},
      {name: 'Verona', country: 'Italy', year: 2000},
      {name: 'Zanzibar City', country: 'Tanzania', year: 2000},
      {name: 'Baku', country: 'Azerbaijan', year: 2000},
      {name: 'Bardejov', country: 'Slovakia', year: 2000},
      {name: 'Saint-Louis', country: 'Senegal', year: 2000},
      {name: 'Lamu', country: 'Kenya', year: 2001},
      {name: 'Guimarães', country: 'Portugal', year: 2001},
      {name: 'Goiás', country: 'Brazil', year: 2001},
      {name: 'Vienna', country: 'Austria', year: 2001},
      {name: 'Essaouira', country: 'Morocco', year: 2001},
      {name: 'Acre', country: 'Israel', year: 2001},
      {name: 'Stralsund', country: 'Germany', year: 2002},
      {name: 'Wismar', country: 'Germany', year: 2002},
      {name: 'Paramaribo', country: 'Suriname', year: 2002},
      {name: 'Tel Aviv', country: 'Israel', year: 2003},
      {name: 'Valparaíso', country: 'Chile', year: 2003},
      {name: 'Berat', country: 'Albania', year: 2005},
      {name: 'Gjirokastra', country: 'Albania', year: 2005},
      {name: 'Cienfuegos', country: 'Cuba', year: 2005},
      {name: 'Yaroslavl', country: 'Russia', year: 2005},
      {name: 'Macao', country: 'China', year: 2005},
      {name: 'Mostar', country: 'Bosnia and Herzegovina', year: 2005},
      {name: 'Harar', country: 'Ethiopia', year: 2006},
      {name: 'Regensburg', country: 'Germany', year: 2006},
      {name: 'Corfu', country: 'Greece', year: 2007},
      {name: 'Camagüey', country: 'Cuba', year: 2008},
      {name: 'George Town', country: 'Malaysia', year: 2008},
      {name: 'Melaka', country: 'Malaysia', year: 2008},
      {name: 'Ribeira Grande', country: 'Cabo Verde', year: 2009},
      {name: 'Bridgetown', country: 'Barbados', year: 2011},
      {name: 'Grand-Bassam', country: "Cote d'Ivoire", year: 2012},
      {name: 'Rabat', country: 'Morocco', year: 2012},
      {name: 'Agadez', country: 'Niger', year: 2013},
      {name: 'Levuka', country: 'Fiji', year: 2013},
      {name: 'Kaesong', country: 'North Korea', year: 2013},
      {name: 'Jeddah', country: 'Saudi Arabia', year: 2014},
      {name: 'Ahmedabad', country: 'India', year: 2017},
      {name: 'Yazd', country: 'Iran', year: 2017},
      {name: 'Sheki', country: 'Azerbaijan', year: 2019},
      {name: 'As-Salt', country: 'Jordan', year: 2021},
      {name: 'Odesa', country: 'Ukraine', year: 2023},
      {name: 'Kuldīga', country: 'Latvia', year: 2023},
    ],
  },
};

/**
 * Check if a city from a list matches the user's visit data.
 * Matches by city name appearing in the CSV city column,
 * or by the city's country being in the country visit data.
 * Returns true if the city's country has been visited AND
 * the city name appears in the visit rows.
 */
export function matchCityVisits(cityList, visitRows, countryData) {
  const visitedCities = new Set();

  /* Build a set of city names from visit rows (case-insensitive) */
  const cityNamesFromRows = new Set();
  for (const row of visitRows) {
    if (row.city) cityNamesFromRows.add(row.city.toLowerCase());
  }

  for (const city of cityList) {
    const cityLower = city.name.toLowerCase();
    /* Direct city name match in visit data */
    if (cityNamesFromRows.has(cityLower)) {
      visitedCities.add(city.name);
      continue;
    }
    /* Also check if country was visited AND city name appears
       as a substring in any visit row city field */
    if (countryData.has(city.country)) {
      for (const row of visitRows) {
        if (row.city && row.city.toLowerCase().includes(cityLower)) {
          visitedCities.add(city.name);
          break;
        }
      }
    }
  }

  return visitedCities;
}
